### ISSUE TITLE
second page - save beside trash can

### ISSUE THREAD

**Issue by josephrbennett** [NCC-CNC/whattemplatemaker#19]
I wonder if it's possible to adjust the "save" beside trash can on map editing feature. I can see what it does (confirm deletion), but wonder if it might confuse. Maybe it's just me?

**Comment by jeffreyhanson** [comment]
Yeah, I agree that it's not immediately clear what it does. Since the functionality for editing the map is mostly from the mapedit R package (https://github.com/r-spatial/mapedit), it wouldn't be trivial for me to update the behavior for the delete button (i.e. that you need to click save in order for the changes to persist). E.g., I'd have to re-write a lot of R and JS code to implement this. Maybe this is something we could cover in the manual for the WTD tool?

**Comment by josephrbennett** [comment]
agree!
