### ISSUE TITLE
Excel spreadsheet failed to download

### ISSUE THREAD

**Issue by josephrbennett** [NCC-CNC/whattemplatemaker#23]
Wasn't clear to me if this was a timeout issue or something more fundamental. If the former, perhaps there needs to be a warning? I was using it fairly consistently.

**Comment by jeffreyhanson** [comment]
Thanks for reporting this - it sounds like a serious issue that could be very annoying for users - I'll look into it.

**Comment by jeffreyhanson** [comment]
I was able to reproduce the error, here's what happening.

Basically, Excel has a hard limit of 31 characters for sheet names. Since the character-limit for site/action/feature ids is 20 characters and sheet names are named according to `Consequence of "{x}"` (where `x` is an id, such as `Fire management (T)`), this means that it is possible to trick R into trying to create an Excel spreadsheet with more than 31 characters. This causes R to throw an error internally when preparing the download file, in turn, causes the download to fail. 

To fix this, we need to (a) reduce the maximum character limit for the site/action/feature ids should be 14, or (b) update the nmaing convention to use fewer characters (so the total sheet name with the id following naming convention does not exceed 31 characters in total).

**Comment by ricschuster** [comment]
Thanks @jeffreyhanson!
I would vote for ids of a maximum of 17 characters. Seems the most straight forward thing here.

**Comment by josephrbennett** [comment]
Agree. Thanks a lot for sleuthing it out! This is another thing to mention in the manual. How should we track these? Is there a label we can use?

**Comment by jeffreyhanson** [comment]
Ok great - I'll do that.

Yeah, we could use the `documentation` label to keep track of things related to the documentation - but it might not be ideal because we would have to manually remember to update the labels once the manual has been updated.
