### ISSUE TITLE
Cannot add more than 21 locations before it freezes

### ISSUE THREAD

**Issue by jgvincent** [NCC-CNC/whattemplatemaker#32]
Tried to enter more than 21 locations (201). Tried entering them in batches, and 1 at a time. It always freezes at 21 lines and I cannot scroll down to add more.

**Comment by jeffreyhanson** [comment]
@DanWismer, I can't seem to fix this. Could you please take a look? Specifically, the issue is that the overflow for the site table is hidden. So, when a lot of rows are added to the table, the extra rows do not appear on the page. Although it would seem that this relatively straightforward to fix using a `max-height` attribute, it is not this easy because the table should have a dynamic `max-height` depending on whether the map above the table is displayed or not. This is because if the user displays the map above the table then there is not much room for the table, but if the map is toggled off, then there is lots of room.

**Comment by jeffreyhanson** [comment]
Ok I think I've got it all working now!

**Comment by DanWismer** [comment]
Amazing! What was the solution?

**Comment by jeffreyhanson** [comment]
Yeah, it turns out that the "style" attribute on the Shiny conditional panel has three states. These are(1) the default visible state (before toggled on/off), (2) the non-visible state, and (3) the visible state (after toggling on/off). So, to fix this, I had to create CSS rules for each of the three states (whereas before I only had 2 covered, see https://github.com/NCC-CNC/whattemplatemaker/blob/master/inst/app/www/style.css#L106-L119).
